pipeline {
    agent any
    
    tools {
        maven 'maven-3' 
    }

    stages {
        stage('Compile Project') {
            steps {
                bat 'mvn clean compile'
            }
        }
        
        stage('Run TestNG Tests') {
            steps {
                bat 'mvn test'
            }
        }
    }
}