pipeline {
    agent any
    
    tools {
        maven 'maven-3' 
    }

    stages {
        stage('Compile Project') {
            steps {
                dir('Desktop/devopslab-main') {
                    bat 'mvn clean compile'
                }
            }
        }
        
        stage('Run TestNG Tests') {
            steps {
                dir('Desktop/devopslab-main') {
                    bat 'mvn test'
                }
            }
        }
    }
}